name: Deploy Development

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect VPS and deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./app/practicum-backend
            pm2 delete server
            git checkout dev
            git fetch
            git pull
            yarn install
            rm .env
            ./scripts/start.dev.sh
            rm -rf out
            yarn seed
            yarn build
            pm2 start out/server.js
